### PR TITLE
Adding Google Search Console verification

### PR DESCRIPTION
**Pull request by MylesJarvis**
### Trello card

N/A

### Context

As part of our drive to improve traffic/SEO performance, we need to enable Search console to be able to ask Google to crawl the site with the new robots.txt. This adds a file.

### Changes proposed in this pull request

Add verification file to our main folder.

### CODE REVIEW

**Comment by jkempster34** [comment]
Is this following the html file upload section [here](https://support.google.com/webmasters/answer/9008080?hl=en#html_verification&zippy=%2Chtml-tag%2Chtml-file-upload) because I think it will need to be visitable?

**Comment by MylesJarvis** [comment]
@jkempster34 it needs to be visitable at schoolexperience.eduation.gov/ABC123.html. Does that mean it needs to go in our 'public' folder instead?

**Comment by leoapost** [comment]
> @jkempster34 it needs to be visitable at schoolexperience.eduation.gov/ABC123.html. Does that mean it needs to go in our 'public' folder instead?

Correct

**Comment by MylesJarvis** [comment]
Pushed that update

**Review by leoapost — APPROVED** [review]

**Pull request merged**
