### PR TITLE
Change how onboarded schools update their profile

### PR DESCRIPTION
**Pull request by ethax-ross**
### Trello card

[Trello-525](https://trello.com/c/XyHVRrNW/525-dev-update-our-profile-update-page-to-save-automatically-when-a-section-is-saved-in-the-flow)

### Context

If a school has onboarded and they edit their profile, we are finding that they get to the preview profile page and assume their changes have been saved. They do not realise that they need to scroll to the bottom of the profile preview
page to publish their changes.

To avoid this confusion, when a school has onboarded and they view their profile then go on to edit one of the sections we want to save the changes as soon as they have filled in the section (which may be multiple steps) and show a success notification on the preview page.

### Changes proposed in this pull request

- Remove publish warning for onboarded schools
- Remove preview profile save changes warning
- Save changes on editing individual steps when onboarded

### Guidance to review

If a school gets halfway through editing a step but doesn't finish, then navigate away and come back to 'update your school profile' they will be re-inserted into the edit flow where they left off instead of viewing the profile. I think this is fine, but worth pointing out.

| Onboarded - View Profile      | Onboarded - After Edit | I Onboarded - Preview | Onboarding - View Profile | Onboarding - Preview |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| screencapture-localhost-3000-schools-on-boarding-profile-2022-02-11-10_33_36      | screencapture-localhost-3000-schools-on-boarding-profile-2022-02-11-10_33_52      | screencapture-localhost-3000-schools-on-boarding-preview-2022-02-11-10_34_33       | screencapture-localhost-3000-schools-on-boarding-profile-2022-02-11-10_36_17      | screencapture-localhost-3000-schools-on-boarding-preview-2022-02-11-10_36_49       |

### CODE REVIEW

**Review by jkempster34 — APPROVED** [review]
LGTM 💯 

Would these buttons be better if they said "Save changes" or "Save changes and continue"?
image

**Comment by MylesJarvis** [comment]
BugUpdateProfile

@ethax-ross having an issue with updating profile in the review app, unsure why this might be. It doesn't jump to a check answers page (does this on numerous schools).

**Comment by jkempster34** [comment]
> BugUpdateProfile
> 
> @ethax-ross having an issue with updating profile in the review app, unsure why this might be. It doesn't jump to a check answers page (does this on numerous schools).

Its throwing an error because I removed a database column [here](https://github.com/DFE-Digital/schools-experience/pull/2297), and the review apps share a database. I think it will need rolling back for this review app the work properly

**Comment by MylesJarvis** [comment]
🚢  LGTM, works as expected.

**Pull request merged**
