### PR TITLE
Updated copy on 'what do you want to get out of your placement'

### PR DESCRIPTION
**Pull request by MylesJarvis**
### Trello card

https://trello.com/c/fPGzH82A

### Context

Analysis of what users typed in this question suggested we could be a bit more general in terms of what they wrote when we asked what they wanted to get out of their school experience.

### Changes proposed in this pull request

Update copy to version by @B-Bonner.

### Guidance to review

Previous: 
image

### CODE REVIEW

**Comment by B-Bonner** [comment]
I'm happy with the words, I'd just like Gary to take a look at it too, from a design perspective. (couldn't find his name when looking for reviewers).

**Here's the new version:**

Screenshot 2021-11-17 at 08 43 20

**Comment by B-Bonner** [comment]
There are currently 2 questions that appear on this page (depending on whether a school has fixed or flexible dates). These questions need to be split over 2 pages: 

- 1st page 'When are you available for school experience?'
- 2nd page 'What do you want to get out of your school experience?'

That will also allow us to remove the 'Request school experience' heading 1. We won't need it if we make the questions the heading 1s.

**Comment by MylesJarvis** [comment]
> There are currently 2 questions that appear on this page (depending on whether a school has fixed or flexible dates). These questions need to be split over 2 pages:
> 
> * 1st page 'When are you available for school experience?'
> * 2nd page 'What do you want to get out of your school experience?'
> 
> That will also allow us to remove the 'Request school experience' heading 1. We won't need it if we make the questions the heading 1s.

Indeed. This will need a bit of dev capacity to do. It's not top of the priority list at the moment, but it is on my radar.

**Comment by MylesJarvis** [comment]
> I'm happy with the words, I'd just like Gary to take a look at it too, from a design perspective. (couldn't find his name when looking for reviewers).
> 
> **Here's the new version:**
> 
> Screenshot 2021-11-17 at 08 43 20

Paging @gazcarr

**Review by jkempster34 — APPROVED** [review]
✅

**Pull request merged**
