### PR TITLE
Sms messages

### PR DESCRIPTION
**Pull request by jkempster34**
### Trello card
[Trello](https://trello.com/c/Vt2y63Sd)

### Context
We want to improve candidate attendance, and think sending them additional SMS reminders might help.

### Changes proposed in this pull request
- Split notify jobs and despatchers into SMS and email

### Guidance to review
I thought we could get this base code merged, then add the SMSs in a separate PR.

Note: everything related to "despatch" is spelt that way already throughout, I think its just ye olde 
image

### CODE REVIEW

**Comment by jkempster34** [comment]
@leoapost Could I have a quick review just to check everything looks okay before we think about content and stuff?

**Comment by leoapost** [comment]
> @leoapost Could I have a quick review just to check everything looks okay before we think about content and stuff?

From a quick look it looks ok. 

There's room for improvements around the namespaces and the class names, but not a biggie, ie:

```
Notify::Dispatchers::Base

Notify::Dispatchers::Sms < Notify::Dispatchers::Base
Notify::Sms::CandidateBookingReminder < Notify::Dispatchers::Sms

Notify::Dispatchers::Email < Notify::Dispatchers::Base
Notify::Email::CandidateBookingCancellation < Notify::Dispatchers::Email

# Jobs
Notify::BaseJob
Notify::SmsJob < Notify::BaseJob
Notify::EmailJob < Notify::BaseJob
```

**Comment by jkempster34** [comment]
> > @leoapost Could I have a quick review just to check everything looks okay before we think about content and stuff?
> 
> From a quick look it looks ok.
> 
> There's room for improvements around the namespaces and the class names, but not a biggie, ie:
> 
> ```
> Notify::Dispatchers::Base
> 
> Notify::Dispatchers::Sms < Notify::Dispatchers::Base
> Notify::Sms::CandidateBookingReminder < Notify::Dispatchers::Sms
> 
> Notify::Dispatchers::Email < Notify::Dispatchers::Base
> Notify::Email::CandidateBookingCancellation < Notify::Dispatchers::Email
> 
> # Jobs
> Notify::BaseJob
> Notify::SmsJob < Notify::BaseJob
> Notify::EmailJob < Notify::BaseJob
> ```

I did the best I could with this. I think it was conflicted because the Notify Jobs aren't wrapped in a Job module.

**Review by leoapost — APPROVED** [review]
Looks good to me

**Pull request merged**
