### PR TITLE
Add DDoS protection

### PR DESCRIPTION
**Pull request by leoapost**
### Trello card
https://trello.com/c/XAIC00Le

### Context
We want to protect the app from hostile bots which pollute our db with spam and can also cause DDoS attacks.

### Changes proposed in this pull request
Add Fail2Ban to ban hostile bots and Rack::Attack to throttle requests to transaction endpoints.

The ban is set to 5mins per ip and the throttling to 5 req/ip.

If a user encounters a rate limit, the app will redirect the request to a 'Too many requests' error page.

### CODE REVIEW

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1755-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1755-website.azurewebsites.net

**Review by ethax-ross — COMMENTED** [review]
In the app/TTA service we have a gem that provides cloudfront IP addresses to ensure we don't ban cloudfront by accident; I'm not sure if SE uses cloudfront, but given we're migrating it just now to GOV PASS I think it would be worth doing this ahead of the migration?

https://github.com/DFE-Digital/get-into-teaching-app/blob/master/Gemfile#L61-L62

https://github.com/DFE-Digital/get-into-teaching-app/blob/7d07d3bd83ab4b2dd5d97ca18dfe75438fca20d5/lib/cloud_front_ip_filter.rb#L3

**Comment by leoapost** [comment]
> In the app/TTA service we have a gem that provides cloudfront IP addresses to ensure we don't ban cloudfront by accident; I'm not sure if SE uses cloudfront, but given we're migrating it just now to GOV PASS I think it would be worth doing this ahead of the migration?
> 
> https://github.com/DFE-Digital/get-into-teaching-app/blob/master/Gemfile#L61-L62
> 
> https://github.com/DFE-Digital/get-into-teaching-app/blob/7d07d3bd83ab4b2dd5d97ca18dfe75438fca20d5/lib/cloud_front_ip_filter.rb#L3

Yeah, actually that's a good idea. I'm going to port the GiT implementation to SE.

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1755-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1755-website.azurewebsites.net

**Review by ethax-ross — APPROVED** [review]

**Review by peteryates — COMMENTED** [review]
Makes sense to me

**Pull request merged**
