### PR TITLE
Remove all references to service updates

### PR DESCRIPTION
**Pull request by MylesJarvis**
### Trello card

https://trello.com/c/TnZSL915

### Context

We no longer want to have service updates on the GSE service, as it's an outdated mechanism for telling users about changes and we have been sporadic in creating these updates. This PR removes the functionality completely.

### Changes proposed in this pull request

- Remove the service update references from any front end pages
- remove service update values from any files that help produce the service update pages and listing/indexing on the backend
- Remove the service update references from any tests
- Prevent a cookie being placed in relation to service update
- Remove the service update cookie from the cookie policy

### Guidance to review

- Review with whitespace removed on the diff. Use this link: https://github.com/DFE-Digital/schools-experience/pull/3208/files?diff=split&w=1

### CODE REVIEW

**Review by martyn-w — APPROVED** [review]
👍  excellent work 👍

**Comment by gemmadallmandfe** [comment]
@MylesJarvis @martyn-w 

Is it worth adding a wildcard redirect from `/service_updates` (and all sub-pages) for tidiness, to cover all the deleted pages?

Should probably go to `/schools/dashboard`?

**Comment by gemmadallmandfe** [comment]
@MylesJarvis You are removing reference to the cookie being dropped from the cookie policy - do we need to remove the cookie itself (GTM?)

If so, we have a cookies ticket in the GSE backlog - can you add this?

**Comment by MylesJarvis** [comment]
This has in fact deployed - redirect is working @gemmadallmandfe

**Review by martyn-w — APPROVED** [review]
👍  LGTM

**Pull request merged**
