### PR TITLE
adding timings check script

### PR DESCRIPTION
**Pull request by petenorth**
### Context

The School Experience application should be consistently responsive. To this end we the continuous deployment pipeline will record response times of the cucumber tests when they run against the application deployed into the development environment.

### Changes proposed in this pull request

A python script has been written which processes the cucumber json output. It takes two arguments, the first argument is the location of the cucumber test result json file and the second is the minimum response time in nano seconds.

### Guidance to review

The output of the script is something like

    2019-02-15T13:55:44.4004211Z [command]"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe" D:\a\_temp\eb3ffee2-b9b2-4136-b386-0ba120f8b852.py reports/cucumber-chrome.json 2000000000
    2019-02-15T13:55:47.2395386Z Duration 22.00s > 2.00 candidate-landing-page candidate-landing-page;page-heading I am on the 'landing' page
    2019-02-15T13:55:47.2395719Z Duration 2.41s > 2.00 background-checks background-checks;form-contents I should see radio buttons for 'Do you have a Disclosure and Barring Service (DBS) check document?' with the following options:
    2019-02-15T13:55:47.2396012Z Duration 2.42s > 2.00 background-checks background-checks;filling-in-and-submitting-the-form I choose 'Yes' from the 'Do you have a Disclosure and Barring Service (DBS) check document?' radio buttons
    2019-02-15T13:55:47.2396226Z Duration 4.55s > 2.00 request-a-school-experience-placement request-a-school-experience-placement;form-contents I should see a form with the following fields:
    2019-02-15T13:55:47.2396424Z Duration 2.13s > 2.00 entering-candidate-contact-details entering-candidate-contact-details;page-contents I should see a form with the following fields:
    2019-02-15T13:55:47.2396554Z ERROR: some responses were too slow.
    2019-02-15T13:55:47.2515078Z ##[error]C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe failed with return code: 1

### CODE REVIEW

**Comment by peteryates** [comment]
The script looks fine to me (despite it being in Python! 🐍) but I don't think it should be in the root of the app.

Perhaps `script/` would be a more-logical place for it?

AFAIK `script/` is no longer used and the one (automatically-generated) file that's in there isn't needed, so feel free to delete `script/cucumber` too.

**Comment by petenorth** [comment]
@peteryates have responded to your comments.

**Comment by peteryates** [comment]
Additionally, is `--format usage` any use?

It prints an output like this:

```
bundle exec cucumber --format usage
Using the default profile.....................................
0.2726641 "I am on the {string} page"
    # features/step_definitions/common_steps.rb:1 
  2.3812430 Given I am on the 'landing' page
    # features/candidates/landing_page.feature:7
  0.0083420 Given I am on the 'landing' page
    # features/candidates/landing_page.feature:11
  0.0086230 Given I am on the 'landing' page
    # features/candidates/landing_page.feature:15
```

**Comment by petenorth** [comment]
@peteryates 

I did look at --format usage , I decided to go for a json as the data is structured and easily manipulated. Either way a script would be required (one parsing unstructured text output or one parsing structured json) that checked whether the timings were within the specified ranges.

Peter.

**Pull request merged**
