### PR TITLE
Sonarcloud Code Coverage 

### PR DESCRIPTION
**Pull request by sfawcett123**
Sonarcloud is not importing the code coverage report, it seems that the paths change and that causes an error.
Forcing the path to remain constant.

### CODE REVIEW

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1874-website.azurewebsites.net

**Review by saliceti — APPROVED** [review]

**Pull request merged**
