### PR TITLE
Get Healthchecks to display SHA

### PR DESCRIPTION
**Pull request by sfawcett123**
# Improve Healthcheck
The health check script is disabled. We should get this working.

# Tasks
- The file the sha is kept in has the wrong name, this isn't too important but it does not make sense so corrected it.
- When the docker container is built the file /etc/school-experience-sha is populated.
- Change the test script to work for the returned details

# Review
- SHA now displaying https://review-schools-experience-1787.london.cloudapps.digital/healthcheck
- Health check now working

### CODE REVIEW

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1787-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1787-website.azurewebsites.net

**Review by leoapost — COMMENTED** [review]
The indentation of the `tests/confidence/healthcheck.sh` is a bit off, but other than that it looks ok to me

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1787-website.azurewebsites.net

**Review by leoapost — APPROVED** [review]

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1787-website.azurewebsites.net

**Pull request merged**
