### PR TITLE
Invite Users to GSE

### PR DESCRIPTION
**Pull request by ekumachidi**
### Trello card
[#5535 ](https://trello.com/c/KSbGXeZ5)

### Context
We want to Integrate the Identity only version of DfE Sign-in with Get School Experience
Build pages to add users to a school.
Allow school administrators to invite users to the school that they administer through 'School Dashboard'

### Changes proposed in this pull request
- Add link to manage users in school dashboard

### CODE REVIEW

**Comment by MylesJarvis** [comment]
I'm going to add comments as and when I find them from a review, hope that's okay!

https://get-school-experience-review-pr-8.test.teacherservices.cloud/schools/users/new

- At this URL, which is when I've clicked add user from the Manage Users Page (https://get-school-experience-review-pr-8.test.teacherservices.cloud/schools/users)
- We need to style the Title
- We need to ensure that first_name renders as First name
- We need to ensure that last_name renders as Last name
- We need to ensure that the cancel link groups to align with the 'continue' button (see image below from the Gov uk design system)

image

image

**Comment by MylesJarvis** [comment]
When in the Manage users page the link to DFE Sign-In goes to production automatically, should this be environment specific? I ask this as we are pulling the users who have access from (below this paragraph in the image below) Pre-prod DfE Sign In, we should probably link to pre-prod by default. Doing this will allow me to test the functionality of removing a user in the DSI console and seeing it disappear from this page.

- DFE should also be amended to 'DfE'

image

**Comment by MylesJarvis** [comment]
I also have a couple of issues with backlinks and 404 errors when adding a user:

404 error gse

**Comment by ekumachidi** [comment]
> I'm going to add comments as and when I find them from a review, hope that's okay!
> 
> https://get-school-experience-review-pr-8.test.teacherservices.cloud/schools/users/new
> 
> * At this URL, which is when I've clicked add user from the Manage Users Page (https://get-school-experience-review-pr-8.test.teacherservices.cloud/schools/users)
> * We need to style the Title
> * We need to ensure that first_name renders as First name
> * We need to ensure that last_name renders as Last name
> * We need to ensure that the cancel link groups to align with the 'continue' button (see image below from the Gov uk design system)
> 
> image image

This was the original design but I'm happy to make changes as per your feedback image

**Comment by tejasjinaraldfe** [comment]
> Review app deployed to https://get-school-experience-review-pr-3080.test.teacherservices.cloud ✅ DfE sign in route obtained: https://get-school-experience-review-pr-8.test.teacherservices.cloud

@ekumachidi please find below the comments as discussed during testing

1. Add user first step - Firstname & Lastname change to First name & Last name

2. On /schools/users page - DfE Sign-in link should redirect users to /approvals/users on the respective environments

3. On /schools/users page when a new user is invited -

a. If the user already has a DfE Sign-in account:
- They can access the school but do not appear in the user list on the page
- They do not receive any email notification confirming that they have been granted access to manage a new school

b. If the user does not have a DfE Sign-in account:

- They receive an email notification inviting them to create an account on DfE sign-in but does not say anything which service they have been invited to manage or for which organisation
- After then sign-in, they can access the school but do not appear in the user list on the page

4. When the user logs out, they do not get redirected back to the Manage School Experience and see the following error

Error
invalid_request
post_logout_redirect_uri not registered

**Pull request merged**
