### PR TITLE
Enable Deploy to Production

### PR DESCRIPTION
**Pull request by sfawcett123**
# [Trello 121](https://trello.com/c/UclgnRLK/121-add-github-action-to-deliver-to-production)

Execute the terraform that will deploy the application to the production environment.

## Solution
Converted the Code to use Matrix deployments, and then set the matrix up dependant on what the commit type is. 

## Review
The application should not be effected.
Code Changed to use a Matrix approach to the deployments, which permits code-reuse.

### CODE REVIEW

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1879-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1879-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1879-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1879-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1879-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1879-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1879-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1879-website.azurewebsites.net

**Comment by dfe-schoolexperience** [comment]
Review can be found at https://se-review-1879-website.azurewebsites.net

**Review by saliceti — APPROVED** [review]

**Pull request merged**
